[OUTPUT-364][TW-171] Add Native 2.0 sample
Buzzvil/buzz-sdk-samples pull request #101
Opened 2022-10-26 00:56 UTC by MiJey

major reviewer: @george-buzz  

Native 2.0 샘플 코드를 추가합니다.
PR 머지는 3.21.+이 정식 배포 된 후, 최종 테스트 이후에 할 예정입니다.

### 동작 영상

https://user-images.githubusercontent.com/45025283/197909444-04be78f6-0afa-4236-a631-65a5a23dd542.mp4

2022-10-26 01:11 UTC, JuHyang commented on buzzad-benefit/app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
nit : 아래 xml 에서 constraintlayout 사용하는곳이 없어보이네요 !

2022-10-26 01:13 UTC, JuHyang requested changes

2022-10-26 01:13 UTC, JuHyang commented on buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/MainActivity.java
> +        });
같은 파일에 다른 clickListener 와 동일하게 되어있으면 좋을 것 같습니다.

2022-10-26 01:40 UTC, MiJey commented on buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/MainActivity.java
> +        });
캐러셀을 제외한 다른 버튼들은 프래그먼트를 사용하고 있습니다.
액티비티 전환을 하는 경우는 캐러셀 버튼밖에 없는데, 캐러셀은 아래와 같이 스태틱 메서드로 startActivity를 미리 구성해서 사용하고 있습니다. 이렇게 복잡하게 할 필요는 없는 것 같아서 네이티브 2.0 버튼 동작은 setOnClickListener에 간단하게 작성했습니다. 캐러셀 액티비티 처럼 구성하는게 낫겠다고 생각하시면 변경하겠습니당

```
// NativeCarouselActivity.kt
class NativeCarouselActivity : AppCompatActivity() {

    companion object {
        private const val TAG = "NativeCarouselActivity"

        @JvmStatic
        fun startActivity(context: Context) {
            val intent = Intent(context, NativeCarouselActivity::class.java)
            context.startActivity(intent)
        }
    }

// MainActivity.java
nativeCarouselButton.setOnClickListener(v -> {
    NativeCarouselActivity.startActivity(MainActivity.this);
});
```

2022-10-26 01:44 UTC, MiJey commented on buzzad-benefit/app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
이것저것 작업하다가 추가되었었나보네요. 삭제했습니다!

2022-10-26 05:53 UTC, JuHyang commented on buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/MainActivity.java
> +        });
nit 에 가까운 제안이었는데, 제가 설명을 너무 못적었군요.. 죄송함다 :) 
설명해주신 부분은 그대로 두어도 괜찮을것 같아요 ! 
자세한 설명 감사합니당
```suggestion
        nativeAd2Button.setOnClickListener(new View.OnClickListener() {
            Intent intent = new Intent(MainActivity.this, NativeAd2Activity.class);
            startActivity(intent);
        });
```

2022-10-27 05:09 UTC, ybbarng approved these changes
LGTM입니다.

2022-11-01 07:32 UTC, Minkwan-Song approved these changes
LGTM!

2022-12-14 07:48 UTC, closed without merging